# Generated by Django 4.1.5 on 2023-01-21 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'News Feed Subscriber',
            },
        ),
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('simple_logo_to_service', models.ImageField(blank=True, upload_to='')),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('description_in_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Offered Service',
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_or_requirement', models.TextField()),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_type', models.CharField(choices=[('Internship', 'Internship'), ('Graduate Trainee', 'Graduate Trainee'), ('Full working Employee', 'Full working Employee'), ('Part working Employee', 'Part working Employee')], max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('job_branch', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_on', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('qualifications', models.ManyToManyField(blank=True, to='africonnect.qualifications')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunitie',
            },
        ),
    ]
